version: '3.7'
services:
  aws:
    image: localstack/localstack:0.13.0.10
    container_name: 'localstack-s3'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'